namePrefix: production-
namespace: production
commonAnnotations:
  note: Hello, I am production!
resources:
- ../../base
patches:
- path: configmap.yaml
- path: deployment.yaml
- path: route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    env: production
